### ISSUE TITLE
uninitialized constant errors...

### ISSUE THREAD

**Issue by tomjohnson1492** [mfenner/jekyll-pandoc#2]
When I attempt to build my Jekyll site, I get these errors: 

```
Conversion error: Jekyll::Converters::Markdown encountered an error converting 'content/acme/demo.md'.
  Conversion error: uninitialized constant Jekyll::Converters::Markdown::PandocParser::FatalException
jekyll 2.4.0 | Error:  uninitialized constant Jekyll::Converters::Markdown::PandocParser::FatalException
```

is this because some of my markdown syntax doesn't conform to pandoc?

**Comment by emiapwil** [comment]
Encountered the same problem today, went through the code and found that the reason is that the class FatalException has been moved into Jekyll::Errors module in recent Jekyll packages (I've confirmed this with 2.5.2. and 2.5.3).

As in your case, it is very likely that the change was made before Jekyll 2.4. One workaround is to check your configuration and make sure there are no mistakes (you might want to take a look at the pandoc man page), but the preferred way is to modify the package to adapt to the change (I have done so on my laptop but don't know how to make a pull request...).

**Comment by gavinsimpson** [comment]
@tomjohnson1492 I haven't tested it as I'm not using this gem to use Pandoc with my Jekyll blog, but I've had the same error with the plugin this gem is based on. I fixed it by finding all instances of `FatalException` and replacing them with `Jekyll::Errors::FatalException` following the info @emiapwil provided about `FatalException` now being in a different module.

**Comment by ketch** [comment]
I'm having this problem too.  Was it supposed to be fixed?  I don't understand why the issue is closed.

**Comment by emiapwil** [comment]
@ketch It should be fixed with [this patch](https://github.com/mfenner/jekyll-pandoc/commit/9143c2071f3d62d5e678d8622afe90af06bdac73).

**Comment by mfenner** [comment]
@ketch what versions of `jekyll`and `jekyll-pandoc` are you using?

**Comment by ketch** [comment]
Sorry, I looked at the error more closely and saw that I was getting 

    Invalid Markdown processor: Pandoc

as the first error.  I tried a number of things; in the end, it seems that changing the capital "P" to lower-case "p" ("pandoc") made things work.  I find this puzzling since the Readme says to use "Pandoc".  In any case, my issue was probably not related to this.

For the record, I'm using Jekyll 3.3.1 and I've switched to the development version (master) of Jekyll-pandoc.

**Comment by mfenner** [comment]
Good. The Rubygems version is currently the same as the master branch. The `Pandoc` to `pandoc` relates to how custom markdown processors are loaded. Earlier versions of this gem patched jekyll and used `pandoc`, whereas newer versions of `jekyll-pandoc` use the standard jekyll way and expect `Pandoc`. But all seems to me working for you know.

**Comment by yimingli** [comment]
I'm still having the same problem using `jekyll` 3.3.1 and `jekyll-pandoc` 2.0.1. Switching to lower-case "pandoc" in `_config.yml` didn't work.

```
Invalid Markdown processor given: Pandoc
                    Custom processors are not loaded in safe mode
                    Available processors are: rdiscount, kramdown, redcarpet
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2011-04-09-stigler-1966-theory-of-price.md':
                    Bailing out; invalid Markdown processor.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Bailing out; invalid Markdown processor.
```
